os: linux
sudo: false
language: c
compiler: gcc

addons:
    apt:
        packages:
            - doxygen
            - graphviz

before_script:
    - mkdir $HOME/install

script:
    - make
    - make PREFIX=$HOME/install install
